trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- group: DevOps-Common

parameters:
- name: imageTag
  displayName: Docker Image Tag
  type: string
  default: latest

stages:
- stage: Deploy_Dev
  displayName: Deploy to Dev

  jobs:
  - deployment: DeployDev

    displayName: Deploy to AKS Dev

    environment: aks-dev

    strategy:
      runOnce:
        deploy:

          steps:
            - checkout: self

            - task: KubernetesManifest@1
              displayName: Deploy to AKS Dev

              inputs:
                action: deploy
                kubernetesServiceConnection: aks-dev-connection

                namespace: aks-dev

                manifests: |
                  k8s/deployment.yaml
                  k8s/service.yaml
                  k8s/ingress-dev.yaml
                  k8s/secret.yaml
                  k8s/configmap.yaml
                containers: |
                  gurudocker20/flask-cicd-demo:${{ parameters.imageTag }}
                  
- stage: Deploy_Stage
  displayName: Deploy to Stage
  dependsOn: Deploy_Dev
  condition: succeeded()

  jobs:
  - deployment: DeployStage
    displayName: Deploy to AKS Stage
    environment: aks-stage

    strategy:
        runOnce:
          deploy:

            steps:
              - checkout: self

              - task: KubernetesManifest@1
                displayName: Deploy to AKS Stage

                inputs:
                  action: deploy
                  kubernetesServiceConnection: aks-stage-connection

                  namespace: aks-stage

                  manifests: |
                    k8s/deployment.yaml
                    k8s/service.yaml
                    k8s/ingress-stage.yaml
                    k8s/secret.yaml
                    k8s/configmap.yaml

                  containers: |
                    gurudocker20/flask-cicd-demo:${{ parameters.imageTag }}                 

- stage: Deploy_Prod
  displayName: Deploy to Prod
  dependsOn: Deploy_Stage
  condition: succeeded()

  jobs:
  - deployment: DeployProd

    displayName: Deploy to AKS Prod

    environment: aks-prod

    strategy:
      runOnce:
        deploy:

          steps:
            - checkout: self

            - task: KubernetesManifest@1
              displayName: Deploy to AKS Prod

              inputs:
                action: deploy
                kubernetesServiceConnection: aks-prod-connection

                namespace: aks-prod

                manifests: |
                  k8s/deployment.yaml
                  k8s/service.yaml
                  k8s/ingress-prod.yaml
                  k8s/secret.yaml
                  k8s/configmap.yaml
                containers: |
                  gurudocker20/flask-cicd-demo:${{ parameters.imageTag }}
                  
