apiVersion: v1
kind: ConfigMap

metadata:
  name: flask-config

data:
  APP_NAME: {{ .Values.config.appName | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  ENVIRONMENT: {{ .Values.config.environment | quote }}